---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2
    transport:
      name: winrm
    driver:
      guest: :windows
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[boxstarter_test::simple]
    attributes:
